
version: '2.1'
services:
  image:
    extends:
      file: docker-compose-base.yml
      service: base-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_pass} #remove this line if no password required
    container_name: ${CONTAINER_HOST_NAME:-redis}
    hostname: ${CONTAINER_HOST_NAME:-redis}
    ports:
    - "${SERVER_PORT:-6379}:6379"
    volumes:
    - data:/data

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
