version: '2.1'
services:
  image:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_ALPINE_MIRROR=${IMAGE_ARG_ALPINE_MIRROR:-mirror.tuna.tsinghua.edu.cn}
      - IMAGE_ARG_IMAGE_TAG=${IMAGE_ARG_IMAGE_TAG:-3.0.6}
      - IMAGE_ARG_VERSION=${IMAGE_ARG_VERSION:-3.0.6}
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_pass} #remove this line if no password required
    container_name: ${CONTAINER_HOST_NAME:-redis}
    hostname: ${CONTAINER_HOST_NAME:-redis}
    image: ${IMAGE_PREFIX:-cloudready}/${IMAGE_NAME:-redis}:${IMAGE_TAG:-3.0.6-SNAPSHOT}
    networks:
      local-network:
        ipv4_address: 172.16.238.54
        ipv6_address: 2001:3984:3989::54
    ports:
    - "${SERVER_PORT:-6379}:6379"
    volumes:
    - data:/data

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      - subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind