
version: '2.1'
services:
  image:
    extends:
      file: docker-compose-base.yml
      service: base-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_pass} #remove this line if no password required
    container_name: ${CONTAINER_HOST_NAME:-standalone.redis}
    hostname: ${CONTAINER_HOST_NAME:-standalone.redis}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.redis}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/redis/standalone}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.54}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::54}
    ports:
    - "${EXTERNAL_REDIS_6379_PORT:-6379}:6379"
    restart: always
    volumes:
    - data:/data

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
